### ISSUE TITLE
require': cannot load such file -- samanage

### ISSUE THREAD

**Issue by erikcurtis** [SAManage/Samples#11]
I have attempted to run both the Hardware and Departments scripts. Both error with 

        2: from import_departments.rb:3:in `<main>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- samanage (LoadError)

**Comment by cw2908** [comment]
Hi @erikcurtis

Can you check if the samanage gem is installed? The command should be `gem install samanage`.

**Comment by cw2908** [comment]
I will close as there is no response. If you still have issues here, please let us know.
